---
# handlers file for keepalived
- name: restart keepalived
  ansible.builtin.service:
    name: "{{ keepalived_service_name }}"
    state: "restarted"
  register: _servicerestart
  when:
    - _servicestart is not changed

- name: reload keepalived
  ansible.builtin.service:
    name: "{{ keepalived_service_name }}"
    state: "reloaded"
  register: _servicereload
  # when:
  #   - _servicestart is not changed
  #   - _servicerestart is not defined
